name: Template Setup

on:
  push:
    branches:
      - main # Trigger the workflow when changes are pushed to the main branch

jobs:
  create-branches-and-readmes:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Add your PAT secret here

    steps:
      - name: Set Node.js version
        run: |
          sudo apt-get update -y
          sudo apt-get install -y nodejs npm
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "robert.z.lehr@gmail.com"
          git config --global user.name "Robert Lehr"
        shell: bash

      - name: Create branches
        run: |
          git checkout -b development
          git push origin development
          git checkout -b feature1
          git push origin feature1
          git checkout -b feature2
          git push origin feature2
          git checkout -b feature3
          git push origin feature3

      - name: Create README files
        run: |
          touch README.md
          echo "To track automatically all the tools and scripts and dependencies you are using, install pipenv and npm for your Python and JavaScript files respectively. Depending on your OS, I recommend installing packages with one of these package managers: [pip](https://pip.pypa.io/en/stable/), [conda](https://docs.conda.io/en/latest/), or [Homebrew](https://brew.sh/)." > README.md
          git add README.md
          git commit -m "Add README with advice template"
          git push origin main